version: '2'
services:
  web:
    build: .
    working_dir: /code
    command: iris run server.go
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test